name: Bump command

on: issue_comment

jobs:
  bump:
    runs-on: ubuntu-20.04

    steps:
    - name: Check for Command
      id: command
      uses: xt0rted/slash-command-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        command: bump
        reaction: 'true'
        reaction-type: eyes
        allow-edits: 'true'
        permission-level: write

    - name: Act on the command
      run: echo "The command was '${{ steps.command.outputs.command-name }}' with
        arguments '${{ steps.command.outputs.command-arguments }}'"

    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    # Checkout the pull request branch
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        repository: ${{ github.event.client_payload.pull_request.head.repo.full_name
          }}
        ref: ${{ github.event.client_payload.pull_request.head.ref }}

    - uses: expipiplus1/action-automation/bump-version@HEAD
      with:
        packageInfos: |
          update-nix-fetchgit v .
        packageVersions: |
          { "update-nix-fetchgit": "${{ steps.command.outputs.command-arguments }}" }

    - run: |
        git push origin HEAD:${{ github.event.client_payload.pull_request.head.ref }}
