# Based on https://kodimensional.dev/github-actions

name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  cabal:
    name: ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: [latest]
        ghc: [8.6.5, 8.8.4, 8.10.2]
      fail-fast: false

    steps:
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: actions/setup-haskell@v1.1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      name: Cache cabal-store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Install system dependencies
      run: sudo apt-get install libsodium-dev

    - name: Install Nix dependencies
      run: nix-env -f '<nixpkgs>' -iA git nix-prefetch-git

    - name: Build dependencies
      run: |
        cabal update
        cabal build all --only-dependencies --enable-tests --enable-benchmarks --write-ghc-environment-files=always
        mkdir -p $HOME/.local/bin
        cabal install --installdir=$HOME/.local/bin/ tasty-discover
        printf "%s" "$HOME/.local/bin/" >> $GITHUB_PATH

    - name: Build
      run: |
        cabal update
        cabal build all --enable-tests --enable-benchmarks --write-ghc-environment-files=always

    - name: Test
      run: |
        cabal test all --enable-tests

  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v12
    - uses: actions/checkout@v2
    - run: nix-build
